### ISSUE TITLE
Container var/www folder options

### ISSUE THREAD

**Issue by Mvzundert** [You-Are-Digital/yadock#26]
To fix performance issues on OSX we can use the Docker EDGE version and enable the :cached option on the application location folder (/var/www:cached)

This also happens to break when not using OSX (Ubuntu, Windows). 

We should make this an .env file setting instead.

**Comment by Mvzundert** [comment]
See: https://github.com/You-Are-Digital/yadock/pull/27

**Comment by vjanssens** [comment]
Fixed in #27
